Parameters:
  Email:
    Type: String
  CreateUrlsFunctionArn:
    Type: String
  ApprovalRequestTimeoutSeconds:
    Type: Number
    Default: 300 # 5 minutes
Outputs:
  StateMachine:
    Value: !Ref StateMachine
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref Email

  SendApprovalRequestFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: RolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !Ref CreateUrlsFunctionArn
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref Topic

  SendConfirmationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: RolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref Topic

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "states.amazonaws.com"
          Action: "sts:AssumeRole"
      Policies:
        - PolicyName: RolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource:
              - !GetAtt SendApprovalRequestFunction.Arn
              - !GetAtt SendConfirmationFunction.Arn
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref Topic

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StateMachineRole.Arn
      DefinitionString: !Sub |
        {
            "StartAt": "RequestApproval",
            "Version": "1.0",
            "States": {
                "RequestApproval": {
                    "Type": "Task",
                    "Comment": "Step Functions creates a task token and invokes the SendApprovalRequestFunction lambda with it, which uses sfn-callback-urls to create callback URLs for approve/reject and use SNS to send an approval email with the URLs. When the user clicks on one, it invokes the sfn-callback-urls API Gateway, which then sends success or failure (for the RequestApproval state) back to Step Functions using the task token embedded in the URL. Either outcome proceeds to the SendConfirmation state.",
                    "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
                    "Parameters": {
                        "FunctionName": "${SendApprovalRequestFunction}",
                        "Payload": {
                            "name_in_input.$": "$.name",
                            "token.$": "$$.Task.Token"
                        }
                    },
                    "TimeoutSeconds": ${ApprovalRequestTimeoutSeconds},
                    "ResultPath": "$.output",
                    "Next": "SendConfirmation",
                    "Catch": [
                        {
                            "ErrorEquals": [ "rejected" ],
                            "ResultPath": "$.output",
                            "Next": "SendConfirmation"
                        },
                        {
                            "ErrorEquals": [ "States.Timeout" ],
                            "ResultPath": "$.output",
                            "Next": "SendConfirmation"
                        }
                    ]
                },
                "SendConfirmation": {
                    "Type": "Task",
                    "Comment": "Use the SendConfirmationFunction lambda to send a confirmation email about the the success or failure of the approval step.",
                    "Resource": "arn:aws:states:::lambda:invoke",
                    "Parameters": {
                        "FunctionName": "${SendConfirmationFunction}",
                        "Payload": {
                            "output.$": "$.output"
                        }
                    },
                    "End": true
                }
            }
        }

  SendApprovalRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Timeout: 10
      Role: !GetAtt SendApprovalRequestFunctionRole.Arn
      Handler: index.lambda_handler
      Environment:
        Variables:
          CREATE_URLS_FUNCTION_ARN: !Ref CreateUrlsFunctionArn
          TOPIC_ARN: !Ref Topic
          TIMEOUT_SECONDS: !Ref ApprovalRequestTimeoutSeconds
      Code:
        ZipFile: |
          import json, os, boto3, datetime, time
          def lambda_handler(event, context):
              print('Event:', json.dumps(event))

              expiration = datetime.datetime.now(datetime.UTC) + datetime.timedelta(seconds=int(os.environ['TIMEOUT_SECONDS']))
              print('Expiration:', expiration.isoformat())

              # This input creates two URLs, one for approval (causes the state to succeed) and one for failure (causes the state to fail).
              # We embed outputs that include the name we've been provided.
              input = {
                  "token": event['token'],
                  "actions": [
                      {
                          "name": "approve",
                          "type": "success",
                          "output": {
                              "name_in_output": event['name_in_input']
                          }
                      },
                      {
                          "name": "reject",
                          "type": "failure",
                          "error": "rejected",
                          "cause": event['name_in_input'] + " rejected it"
                      }
                  ],
                  "expiration": expiration.isoformat()
              }

              # Use the sfn-callback-urls Lambda function for creating the URLs. There's also an API Gateway option.
              t1 = time.time()
              response = boto3.client('lambda').invoke(
                  FunctionName=os.environ['CREATE_URLS_FUNCTION_ARN'],
                  Payload=json.dumps(input)
              )
              t2 = time.time()
              urls = json.loads(response['Payload'].read())['urls']
              print('Got URLs:', json.dumps(urls))
              print('Call duration:', t2-t1)

              email_subject = 'Step Functions example approval request'

              email_body = """Hello {name},
              Click below (these could be better in HTML emails):

              Approve:
              {approve}

              Reject:
              {reject}

              These links expire in {timeout} seconds.
              """.format(
                  name=event['name_in_input'],
                  approve=urls['approve'],
                  reject=urls['reject'],
                  timeout=os.environ['TIMEOUT_SECONDS']
              )


              print('Sending email:\r' + email_body.replace('\n', '\r'))
              # replacing newlines with carriage returns makes CloudWatch Logs
              # show it as one entry of multiline text

              boto3.client('sns').publish(
                  TopicArn=os.environ['TOPIC_ARN'],
                  Subject=email_subject,
                  Message=email_body
              )
              print('Done')
              return {}

  SendConfirmationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Timeout: 10
      Role: !GetAtt SendConfirmationFunctionRole.Arn
      Handler: index.lambda_handler
      Environment:
        Variables:
          TOPIC_ARN: !Ref Topic
      Code:
        ZipFile: |
          import json, os, boto3
          def lambda_handler(event, context):
              print('Event:', json.dumps(event))

              email_subject = 'Step Functions example complete'

              if 'Error' in event['output']:
                  if event['output']['Error'] == 'States.Timeout':
                      email_body = """Hello,
                      The approval request timed out.
                      """
                  else:
                    email_body = """Hello,
                    The approval was rejected: {cause}
                    """.format(
                        cause=event['output']['Cause']
                    )
              else:
                  email_body = """Hello {name},
                  The approval was granted.
                  """.format(
                      name=event['output']['name_in_output']
                  )

              print('Sending email:\r' + email_body.replace('\n', '\r'))
              # replacing newlines with carriage returns makes CloudWatch Logs
              # show it as one entry of multiline text

              boto3.client('sns').publish(
                  TopicArn=os.environ['TOPIC_ARN'],
                  Subject=email_subject,
                  Message=email_body
              )
              print('Done')
              return {}
